# Basic data types used in Tax Foundation data. This file includes their names ( used
# to declare used in a metadata file), whether or not the type is sortable, a
# description, and a regular expression to validate that data correctly matches
# the expectation.
data-types:
  - name: numeric
    sortable: true
    description: >
      Numeric data are decimal-formatted numbers. There are no commas, nor any other signs
      (e.g., $, %, etc.).
    regex: '/^-?\d+(?:\.\d+)?$/'
  - name: percentage
    sortable: true
    description: >
      Percentage is a decimal-formatted number between zero and one.
      This data should not be formatted with a % sign at the end--this will
      be added automatically by scripts that output data in various formats.
    regex: '/^-?0?\.+\d+$|^0$|^1$/'
  - name: text
    sortable: true
    description: >
      Any kind of textual data. This kind of data is qualitative.
    regex: '/.?/'
  - name: date
    sortable: true
    description: >
      Dates represent specific dates. Time-of-day information is not included.
      Dates follow the US format of MM-DD-YYYY. Leading zeroes may be omitted,
      though this is not preferred. Usage of / or another delimitter between
      values is not premitted.
    regex: '/^(?:0?[1-9]|1[012])-(?:0?[1-9]|[12][0-9]|3[01])-(?:1[789]|20)\d\d$/'